version: "1.0"

services:
  postgres:
    container_name: np-postgresDb
    image: postgres:9.6
    ports:
      - "5434:5432"
    volumes:
      - ./registry_price_paid.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./pp-monthly-update-new-version.csv:/pp-monthly-update-new-version.csv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
